### ISSUE TITLE
Build failure on padl-generator-pagerank, padl-serialiser-jos

### ISSUE THREAD

**Issue by yihsuan1102** [ptidejteam/ptidej-Ptidej#3]
There is a compilation failure on padl-generator-pagerank.
```
[ERROR] Failed to execute goal on project padl-generator-pagerank: 
Could not resolve dependencies for project net.ptidej.padl:padl-generator-pagerank:jar:1.0.0: 
The following artifacts could not be resolved: net.ptidej.padl:padl-creator-cpp-eclipse:jar:1.0.0 (absent): 
Could not find artifact net.ptidej.padl:padl-creator-cpp-eclipse:jar:1.0.0 in central (https://repo.maven.apache.org/maven2) -> [Help 1]
```
I commented `padl-generator-pagerank` module in `pom.xml`. On subsequent installation, another testing error occurred on padl-serialiser-jos.
```
[INFO] Running padl.serialiser.test.ArgoUML0198Test
[ERROR] Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.315 s <<< FAILURE! -- in padl.serialiser.test.ArgoUML0198Test
[ERROR] padl.serialiser.test.ArgoUML0198Test.testComparator -- Time elapsed: 0.292 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "Object.getClass()" because "in" is null
        at java.base/java.io.Reader.<init>(Reader.java:179)
        at java.base/java.io.BufferedReader.<init>(BufferedReader.java:100)
        at java.base/java.io.BufferedReader.<init>(BufferedReader.java:115)
        at java.base/java.io.LineNumberReader.<init>(LineNumberReader.java:82)
        at padl.serialiser.util.MethodInvocationDeserialiserHelper.<init>(MethodInvocationDeserialiserHelper.java:57)
        at padl.serialiser.JOSSerialiser.deserialise(JOSSerialiser.java:76)
        at padl.serialiser.test.ArgoUML0198Test.setUp(ArgoUML0198Test.java:70)
        at junit.framework.TestCase.runBare(TestCase.java:140)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[ERROR] padl.serialiser.test.ArgoUML0198Test.testNames -- Time elapsed: 0.001 s <<< ERROR!
java.lang.NullPointerException: Cannot invoke "padl.kernel.IAbstractModel.getDisplayName()" because "padl.serialiser.test.ArgoUML0198Test.SerialisedModel" is null
        at padl.serialiser.test.ArgoUML0198Test.testNames(ArgoUML0198Test.java:87)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at junit.framework.TestCase.runTest(TestCase.java:177)
        at junit.framework.TestCase.runBare(TestCase.java:142)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:130)
        at junit.framework.TestSuite.runTest(TestSuite.java:241)
        at junit.framework.TestSuite.run(TestSuite.java:236)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:90)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[ERROR] Errors:
[ERROR]   ArgoUML0198Test.setUp:70 罈 NullPointer Cannot invoke "Object.getClass()" because "in" is null
[ERROR]   ArgoUML0198Test.testNames:87 NullPointer Cannot invoke "padl.kernel.IAbstractModel.getDisplayName()" because "padl.serialiser.test.ArgoUML0198Test.SerialisedModel" is null
```

**Comment by yann-gael** [comment]
You're right, and there were two problems here.

Forst, these two tests, `padl.serialiser.test.ArgoUML0198Test` and `padl.serialiser.test.ArgoUML020Test`, should not run because they refer to resources that are outside of the whole project:

```
				((ICodeLevelModel) ArgoUML0198Test.OriginalModel)
					.create(new LightClassFileCreator(
						new String[] { "../../P-MARt Workspace/ArgoUML v0.19.8/bin/" },
						true));
```

The second problem is that part the code was using the "wrong" model name, which was pointing to resources that I have on my computer but that are not part of the project.

I'm committing a fix now...

**Comment by yann-gael** [comment]
https://github.com/ptidejteam/ptidej-Ptidej/commit/243bd7fe77826f2d1a144fb899573d04d4117c41

**Comment by yihsuan1102** [comment]
`padl-generator-pagerank`  which related to C++ might also be commented in  `pom.xml` the latest commit?
https://github.com/ptidejteam/ptidej-Ptidej/blob/243bd7fe77826f2d1a144fb899573d04d4117c41/pom.xml#L53
